# Generated by Django 4.2.3 on 2023-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='after_09',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='after_11',
            field=models.BooleanField(default=True),
        ),
    ]
