# Generated by Django 4.2.3 on 2023-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_spec_after_09_spec_after_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='after_09',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='spec',
            name='after_11',
            field=models.BooleanField(),
        ),
    ]
