# Generated by Django 4.2.3 on 2023-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_spec_address_spec_period_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='after_09',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='after_11',
            field=models.BooleanField(default=True),
        ),
    ]
