# Generated by Django 4.2.3 on 2023-07-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_type', models.CharField(max_length=255)),
                ('originals', models.CharField(default='Не сдан', max_length=10)),
                ('avg_marks', models.DecimalField(decimal_places=2, max_digits=3)),
                ('certificate_number', models.CharField(max_length=50)),
                ('spec_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.spec', to_field='code')),
            ],
        ),
    ]
