# Generated by Django 4.2.3 on 2023-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='financing_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='originals',
            field=models.BooleanField(default=False),
        ),
    ]
