# Generated by Django 4.2.3 on 2023-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avgs', '0002_alter_application_financing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.BooleanField(default=True),
        ),
    ]
