# Generated by Django 4.2.3 on 2023-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avgs', '0003_application_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('q_ty', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
